/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://pnsuwvussbaoxciqnurhvkc5pa.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ijnqq7bcurajpdunqsx5l73tpm",
    "aws_cognito_identity_pool_id": "us-east-2:86731b76-e955-4fd9-a7fa-a708b68c17a8",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_QLfkSWCjs",
    "aws_user_pools_web_client_id": "1pq7rn2q8rhdprlqbn3b649ln0",
    "oauth": {},
    "aws_user_files_s3_bucket": "amplifynextdce5f9b939914d8fbbe06ae08ee60999164049-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
